# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "FlatBlog Theme"
license = "MIT"
licenselink = "https://github.com/fb64/hugo-flatblog-theme/blob/master/LICENSE.md"
description = "A flat theme for the Hugo static website engine"
homepage = "https://github.com/hugo-flatblog-theme"
tags = ["flat", "bootstrap", "font-awesome"]
features = ["responsive", "mobile-friendly"]
min_version = 0.14

[author]
  name = "Florian Bernard"
  homepage = "https://github.com/fb64"

# If porting an existing theme
[original]
  name = "Phlat Theme"
#  homepage = "https://github.com/nraboy/hugo-phlat-theme"
  repo = "https://github.com/nraboy/hugo-phlat-theme"
